name: pycallgraph

channels:
  - conda-forge
  - default

dependencies:
  - python=3.7
  - ipython=7.19.0
  - graphviz=2.38
  - memory_profiler=0.58.0
  - requests=2.25.1
  - pre-commit=2.9.3
  - psutil=5.7.2
  - pytest=6.2.1
  - pip=20.3.3